const DashboardPage = () => {
  return (
    <div className="">
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>END</div>
    </div>
  );
};

export default DashboardPage;
